name: Run tests on gh actions

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  setup-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v -s
        env:
          OANDA_DEMO_API_KEY: ${{ secrets.OANDA_DEMO_API_KEY }}